"""
evaluate.py

Runs the held-out test set through both the frozen base model and the
fine-tuned PEFT (LoRA) model, computes ROUGE scores against ground-truth
targets, saves quantitative + qualitative results, and auto-generates
evaluation_report.md if it doesn't already exist.

Run as a module from the project root so imports resolve correctly:
    python -m src.evaluate --config configs/training_config.yaml

Note on invocation: this file is intentionally run via `python -m
src.evaluate` rather than `python src/evaluate.py`. Running it directly
would put `src/` at the front of sys.path, and since this very file is
named `evaluate.py`, `import evaluate` (the Hugging Face metrics package)
would resolve to itself instead of the installed library. Running as a
module from the project root avoids that entirely.
"""

import argparse
import json
import logging
import os
from datetime import datetime, timezone

import evaluate as hf_evaluate
import torch
import yaml
from datasets import load_dataset

from src.model_utils import load_model_and_tokenizer, load_peft_model_for_inference

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Config file not found: {config_path}")
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def generate_responses(model, tokenizer, prompts, max_new_tokens: int = 128):
    """
    Generates text predictions for a list of prompts.

    Loop through prompts, tokenize, generate(), decode — batching one at a
    time for simplicity/robustness across different model architectures.
    """
    predictions = []
    model.eval()
    for prompt in prompts:
        inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=2048).to(model.device)
        try:
            with torch.no_grad():
                output_ids = model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    do_sample=False,
                    temperature=1.0,
                    eos_token_id=tokenizer.eos_token_id,
                    pad_token_id=tokenizer.pad_token_id,
                )
        except torch.cuda.OutOfMemoryError as e:
            raise RuntimeError(
                "CUDA out of memory during generation. Try lowering "
                "evaluation.max_new_tokens in the config, or free up VRAM "
                f"by closing other GPU applications. Original error: {e}"
            ) from e
        generated = output_ids[0][inputs["input_ids"].shape[1]:]
        decoded = tokenizer.decode(generated, skip_special_tokens=True).strip()
        predictions.append(decoded)
    return predictions


def calculate_metrics(predictions, references):
    """
    Calculates ROUGE scores comparing predictions to ground truth.
    """
    rouge = hf_evaluate.load("rouge")
    scores = rouge.compute(predictions=predictions, references=references)
    return scores


def generate_evaluation_report(report_path: str, config: dict, metrics: dict, qualitative: list) -> None:
    """
    Auto-generates evaluation_report.md from real results if the file
    doesn't already exist. Existing reports (e.g. hand-edited ones) are
    never overwritten.
    """
    if os.path.exists(report_path):
        logger.info(f"{report_path} already exists — leaving it untouched. "
                    f"Delete it first if you want a freshly generated report.")
        return

    model_cfg = config["model"]
    lora_cfg = config["lora"]
    ds_cfg = config["dataset"]
    quant_cfg = config["quantization"]
    t_cfg = config["training"]

    base_scores = metrics["base_model"]
    tuned_scores = metrics["fine_tuned_model"]

    def fmt(x):
        return f"{x:.4f}" if isinstance(x, (int, float)) else str(x)

    def delta(k):
        try:
            return f"{tuned_scores[k] - base_scores[k]:+.4f}"
        except (KeyError, TypeError):
            return "n/a"

    lines = []
    lines.append(f"# Evaluation Report: LoRA Fine-Tuning of `{model_cfg['base_model_id']}`")
    lines.append("")
    lines.append(f"*Auto-generated by `src/evaluate.py` on "
                  f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.*")
    lines.append("")
    lines.append("## 1. Setup Summary")
    lines.append("")
    lines.append("| Item | Value |")
    lines.append("|---|---|")
    lines.append(f"| Base model | `{model_cfg['base_model_id']}` |")
    lines.append(f"| Dataset | `{ds_cfg['name_or_path']}` |")
    lines.append(f"| Train / Val / Test split | {ds_cfg['train_split']*100:.0f}% / "
                  f"{ds_cfg['val_split']*100:.0f}% / {ds_cfg['test_split']*100:.0f}% |")
    lines.append(f"| LoRA rank (`r`) / alpha | {lora_cfg['r']} / {lora_cfg['lora_alpha']} |")
    lines.append(f"| Target modules | {', '.join(f'`{m}`' for m in lora_cfg['target_modules'])} |")
    lines.append(f"| Quantization | 4-bit {quant_cfg.get('bnb_4bit_quant_type', 'nf4')}, "
                  f"double quant: {quant_cfg.get('bnb_4bit_use_double_quant', True)} |")
    lines.append(f"| Epochs | {t_cfg['num_train_epochs']} |")
    eff_batch = t_cfg["per_device_train_batch_size"] * t_cfg["gradient_accumulation_steps"]
    lines.append(f"| Effective batch size | {eff_batch} "
                  f"({t_cfg['per_device_train_batch_size']} × "
                  f"{t_cfg['gradient_accumulation_steps']} grad-accum) |")
    lines.append(f"| Learning rate | {t_cfg['learning_rate']}, {t_cfg.get('lr_scheduler_type', 'cosine')} schedule |")
    lines.append(f"| Tracking | TensorBoard — logs under `{t_cfg['output_dir']}/runs` |")
    lines.append("")
    lines.append("## 2. Quantitative Results")
    lines.append("")
    lines.append("ROUGE scores on the held-out test set (never seen during training), "
                  "comparing the frozen base model against the base model + trained LoRA adapter:")
    lines.append("")
    lines.append("| Metric | Base Model | Fine-Tuned Model | Δ |")
    lines.append("|---|---|---|---|")
    all_metric_keys = sorted(set(base_scores.keys()) | set(tuned_scores.keys()))
    for k in all_metric_keys:
        lines.append(f"| {k} | {fmt(base_scores.get(k))} | {fmt(tuned_scores.get(k))} | {delta(k)} |")
    lines.append("")
    lines.append("*(Raw values also available in `outputs/eval_results/metrics.json`.)*")
    lines.append("")
    lines.append("## 3. Qualitative Examples")
    lines.append("")
    for i, ex in enumerate(qualitative, start=1):
        lines.append(f"### Example {i}")
        lines.append("")
        lines.append("**Prompt:**")
        lines.append("```")
        lines.append(ex["prompt"])
        lines.append("```")
        lines.append("")
        lines.append("**Ground truth:**")
        lines.append("```")
        lines.append(ex["ground_truth"])
        lines.append("```")
        lines.append("")
        lines.append("**Base model output:**")
        lines.append("```")
        lines.append(ex["base_model_response"])
        lines.append("```")
        lines.append("")
        lines.append("**Fine-tuned model output:**")
        lines.append("```")
        lines.append(ex["fine_tuned_response"])
        lines.append("```")
        lines.append("")
        lines.append("**Observations:** _<add your own analysis here — e.g. did the "
                      "fine-tuned model adopt the expected tone/format, follow "
                      "instructions more precisely, or reduce hallucination?>_")
        lines.append("")
    lines.append("## 4. Analysis")
    lines.append("")
    lines.append("- **Where fine-tuning helped:** _<summarize concrete improvements "
                  "observed in both metrics and qualitative examples>_")
    lines.append("- **Where it didn't (or regressed):** _<automated metrics for LLMs "
                  "are known to be imperfect — note any mismatch between ROUGE and "
                  "your own reading of the qualitative examples>_")
    lines.append("- **Remaining limitations:** _<e.g. hallucination on out-of-domain "
                  "prompts, formatting inconsistencies, limited generalization>_")
    lines.append("")
    lines.append("## 5. Conclusion")
    lines.append("")
    lines.append("_<One-paragraph summary of whether LoRA fine-tuning achieved its "
                  "goal for this dataset/task, and what you'd try next (more data, "
                  "higher rank, different target modules, longer training).>_")
    lines.append("")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logger.info(f"Auto-generated {report_path} from evaluation results. "
                f"Fill in the '<...>' analysis placeholders with your own commentary.")


def main(args: argparse.Namespace):
    config = load_config(args.config)
    ds_cfg = config["dataset"]
    model_cfg = config["model"]
    quant_cfg = config["quantization"]
    train_cfg = config["training"]
    eval_cfg = config["evaluation"]

    if not torch.cuda.is_available():
        raise RuntimeError(
            "No CUDA GPU is visible — evaluation cannot proceed.\n"
            "  Colab: Runtime > Change runtime type > GPU, then rerun this cell.\n"
            "  Local/Windows: confirm `nvidia-smi` works and your driver is current.\n"
            "  Docker: verify GPU passthrough with:\n"
            "    docker run --rm --gpus all nvidia/cuda:12.2.0-base-ubuntu22.04 nvidia-smi"
        )

    test_file = eval_cfg["test_file"]
    if not os.path.exists(test_file):
        raise FileNotFoundError(
            f"{test_file} not found. Run `python -m src.data_pipeline "
            f"--config {args.config}` first."
        )

    logger.info(f"Loading test dataset from {test_file}...")
    test_dataset = load_dataset("json", data_files=test_file, split="train")
    if len(test_dataset) == 0:
        raise ValueError(f"{test_file} is empty — re-run data_pipeline.py.")
    logger.info(f"Test set size: {len(test_dataset)}")

    prompts = list(test_dataset["prompt"])
    targets = list(test_dataset["target"])

    results_dir = eval_cfg["results_dir"]
    os.makedirs(results_dir, exist_ok=True)

    # --- 1. Base model (no adapters) ------------------------------------------------
    logger.info("Loading BASE model (no LoRA adapters)...")
    base_model, tokenizer = load_model_and_tokenizer(
        model_cfg["base_model_id"], quant_cfg, model_cfg.get("trust_remote_code", False)
    )
    logger.info("Generating predictions with base model...")
    base_predictions = generate_responses(base_model, tokenizer, prompts, eval_cfg["max_new_tokens"])
    base_scores = calculate_metrics(base_predictions, targets)
    logger.info(f"Base model ROUGE: {base_scores}")

    del base_model
    torch.cuda.empty_cache()

    # --- 2. Fine-tuned PEFT model ----------------------------------------------------
    adapter_path = train_cfg["final_model_dir"]
    logger.info(f"Loading FINE-TUNED model with LoRA adapters from {adapter_path}...")
    peft_model, peft_tokenizer = load_peft_model_for_inference(
        model_cfg["base_model_id"], adapter_path, quant_cfg, model_cfg.get("trust_remote_code", False)
    )
    logger.info("Generating predictions with fine-tuned model...")
    tuned_predictions = generate_responses(
        peft_model, peft_tokenizer, prompts, eval_cfg["max_new_tokens"]
    )
    tuned_scores = calculate_metrics(tuned_predictions, targets)
    logger.info(f"Fine-tuned model ROUGE: {tuned_scores}")

    # --- Save quantitative results -----------------------------------------------------
    metrics_out = {
        "base_model": base_scores,
        "fine_tuned_model": tuned_scores,
    }
    metrics_path = os.path.join(results_dir, "metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(metrics_out, f, indent=2)
    logger.info(f"Saved quantitative metrics -> {metrics_path}")

    # --- Save qualitative examples ------------------------------------------------------
    n_qual = min(eval_cfg["num_qualitative_examples"], len(prompts))
    qualitative = []
    for i in range(n_qual):
        qualitative.append(
            {
                "prompt": prompts[i],
                "ground_truth": targets[i],
                "base_model_response": base_predictions[i],
                "fine_tuned_response": tuned_predictions[i],
            }
        )
    qual_path = os.path.join(results_dir, "qualitative_examples.json")
    with open(qual_path, "w") as f:
        json.dump(qualitative, f, indent=2)
    logger.info(f"Saved {n_qual} qualitative examples -> {qual_path}")

    # --- Auto-generate evaluation_report.md if missing -----------------------------------
    generate_evaluation_report(eval_cfg["report_path"], config, metrics_out, qualitative)

    logger.info("Evaluation complete.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate base vs fine-tuned model on held-out test set.")
    parser.add_argument("--config", type=str, default="configs/training_config.yaml")
    args = parser.parse_args()
    main(args)
